# Generated by Django 5.2.7 on 2025-10-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_photo_user_profile_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cover_pic',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='cover_photos/'),
        ),
    ]
