# Generated by Django 5.2.5 on 2025-10-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_date_of_birth_user_gender_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('celebrity', 'Celebrity')], default='user', max_length=20),
        ),
    ]
