# Generated by Django 5.2.5 on 2025-10-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='education',
            field=models.TextField(default='institue-name'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='home_town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='web_link',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work',
            field=models.TextField(default='write work-place'),
        ),
    ]
