# Generated by Django 5.2.7 on 2025-11-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_userprofile_education_userprofile_home_town_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
