# Generated by Django 5.2.5 on 2025-11-14 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_comment_reaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
