# Generated by Django 5.2.7 on 2025-11-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.URLField(blank=True, null=True),
        ),
    ]
