# Generated by Django 5.2.7 on 2025-12-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_post_is_repost_post_original_post_shares_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
