# Generated by Django 5.2.7 on 2025-11-19 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='storyview',
            options={'ordering': ['-viewed_at']},
        ),
        migrations.AlterField(
            model_name='story',
            name='media_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='storyview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_views', to=settings.AUTH_USER_MODEL),
        ),
    ]
