# Generated by Django 5.2.7 on 2025-11-26 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celebrity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='celebrity',
        ),
    ]
