# Generated by Django 5.2.7 on 2025-11-27 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celebrity', '0002_remove_donation_celebrity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='celebrityfollow',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='celebrityfollow',
            name='celebrity',
        ),
        migrations.RemoveField(
            model_name='celebrityfollow',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='celebrityprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paidmessage',
            name='celebrity',
        ),
        migrations.RemoveField(
            model_name='paidmessage',
            name='sender',
        ),
        migrations.DeleteModel(
            name='CelebrityCallSession',
        ),
        migrations.DeleteModel(
            name='CelebrityFollow',
        ),
        migrations.DeleteModel(
            name='CelebrityProfile',
        ),
        migrations.DeleteModel(
            name='PaidMessage',
        ),
    ]
