# Generated by Django 5.2.7 on 2025-11-28 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('celebrity', '0005_chatroom_chatmessage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='celebrity',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
